### ISSUE TITLE
Lyrics cuttoff at right of screen

### ISSUE THREAD

**Issue by mikeyhalla** [paradix/skin.cirrus.extended.v3#102]
I brought this issue up on the [MOD] cirrus Extended forum (I think) and got feedback, however I still am not seeing a change. I know that this type of stuff takes time but wanted to make sure I was in the right place due to me using the latest beta version of Kodi not to mention I also use the dsplayer overlay.
As the topic says, Lyrics are cutoff on the right side of the screen and it would be ideal if the entire lyrics were showing for parties and stuff.
Also, I downloaded the V3.3.1 from here and was wondering how to install the repository for this as the one I found was for v2 and the link is dead.
Thank you guys for this bad ass skin! It kills the others and makes for a great entertainment system.

**Comment by paradix** [comment]
This has been changed with the latest version. Can you please confirm that it's Ok now?

**Comment by mikeyhalla** [comment]
Ah yes, thank you!
